// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.DeliveryPlan;
import com.vmi.domain.DeliveryPlanDataOnDemand;
import com.vmi.domain.DeliveryPlanIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DeliveryPlanIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DeliveryPlanIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DeliveryPlanIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DeliveryPlanIntegrationTest: @Transactional;
    
    @Autowired
    DeliveryPlanDataOnDemand DeliveryPlanIntegrationTest.dod;
    
    @Test
    public void DeliveryPlanIntegrationTest.testCountDeliveryPlans() {
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", dod.getRandomDeliveryPlan());
        long count = DeliveryPlan.countDeliveryPlans();
        Assert.assertTrue("Counter for 'DeliveryPlan' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testFindDeliveryPlan() {
        DeliveryPlan obj = dod.getRandomDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to provide an identifier", id);
        obj = DeliveryPlan.findDeliveryPlan(id);
        Assert.assertNotNull("Find method for 'DeliveryPlan' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DeliveryPlan' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testFindAllDeliveryPlans() {
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", dod.getRandomDeliveryPlan());
        long count = DeliveryPlan.countDeliveryPlans();
        Assert.assertTrue("Too expensive to perform a find all test for 'DeliveryPlan', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DeliveryPlan> result = DeliveryPlan.findAllDeliveryPlans();
        Assert.assertNotNull("Find all method for 'DeliveryPlan' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DeliveryPlan' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testFindDeliveryPlanEntries() {
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", dod.getRandomDeliveryPlan());
        long count = DeliveryPlan.countDeliveryPlans();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DeliveryPlan> result = DeliveryPlan.findDeliveryPlanEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DeliveryPlan' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DeliveryPlan' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testFlush() {
        DeliveryPlan obj = dod.getRandomDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to provide an identifier", id);
        obj = DeliveryPlan.findDeliveryPlan(id);
        Assert.assertNotNull("Find method for 'DeliveryPlan' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDeliveryPlan(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DeliveryPlan' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testMergeUpdate() {
        DeliveryPlan obj = dod.getRandomDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to provide an identifier", id);
        obj = DeliveryPlan.findDeliveryPlan(id);
        boolean modified =  dod.modifyDeliveryPlan(obj);
        Integer currentVersion = obj.getVersion();
        DeliveryPlan merged = (DeliveryPlan)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DeliveryPlan' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", dod.getRandomDeliveryPlan());
        DeliveryPlan obj = dod.getNewTransientDeliveryPlan(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DeliveryPlan' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DeliveryPlan' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DeliveryPlanIntegrationTest.testRemove() {
        DeliveryPlan obj = dod.getRandomDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DeliveryPlan' failed to provide an identifier", id);
        obj = DeliveryPlan.findDeliveryPlan(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DeliveryPlan' with identifier '" + id + "'", DeliveryPlan.findDeliveryPlan(id));
    }
    
}
