// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.EstimateUsage;
import com.vmi.domain.EstimateUsageDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EstimateUsageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EstimateUsageDataOnDemand: @Component;
    
    private Random EstimateUsageDataOnDemand.rnd = new SecureRandom();
    
    private List<EstimateUsage> EstimateUsageDataOnDemand.data;
    
    public EstimateUsage EstimateUsageDataOnDemand.getNewTransientEstimateUsage(int index) {
        EstimateUsage obj = new EstimateUsage();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setEstiQ1(obj, index);
        setEstiQ2(obj, index);
        setEstiQ3(obj, index);
        setEstiQ4(obj, index);
        setEstiQ5(obj, index);
        setEstiQ6(obj, index);
        setEstiQ7(obj, index);
        setEstiStartDate(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void EstimateUsageDataOnDemand.setCreatedBy(EstimateUsage obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void EstimateUsageDataOnDemand.setCreatedDate(EstimateUsage obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ1(EstimateUsage obj, int index) {
        Double EstiQ1 = new Integer(index).doubleValue();
        obj.setEstiQ1(EstiQ1);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ2(EstimateUsage obj, int index) {
        Double EstiQ2 = new Integer(index).doubleValue();
        obj.setEstiQ2(EstiQ2);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ3(EstimateUsage obj, int index) {
        Double EstiQ3 = new Integer(index).doubleValue();
        obj.setEstiQ3(EstiQ3);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ4(EstimateUsage obj, int index) {
        Double EstiQ4 = new Integer(index).doubleValue();
        obj.setEstiQ4(EstiQ4);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ5(EstimateUsage obj, int index) {
        Double EstiQ5 = new Integer(index).doubleValue();
        obj.setEstiQ5(EstiQ5);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ6(EstimateUsage obj, int index) {
        Double EstiQ6 = new Integer(index).doubleValue();
        obj.setEstiQ6(EstiQ6);
    }
    
    public void EstimateUsageDataOnDemand.setEstiQ7(EstimateUsage obj, int index) {
        Double EstiQ7 = new Integer(index).doubleValue();
        obj.setEstiQ7(EstiQ7);
    }
    
    public void EstimateUsageDataOnDemand.setEstiStartDate(EstimateUsage obj, int index) {
        Date EstiStartDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEstiStartDate(EstiStartDate);
    }
    
    public void EstimateUsageDataOnDemand.setUpdatedBy(EstimateUsage obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void EstimateUsageDataOnDemand.setUpdatedDate(EstimateUsage obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public EstimateUsage EstimateUsageDataOnDemand.getSpecificEstimateUsage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EstimateUsage obj = data.get(index);
        Long id = obj.getId();
        return EstimateUsage.findEstimateUsage(id);
    }
    
    public EstimateUsage EstimateUsageDataOnDemand.getRandomEstimateUsage() {
        init();
        EstimateUsage obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EstimateUsage.findEstimateUsage(id);
    }
    
    public boolean EstimateUsageDataOnDemand.modifyEstimateUsage(EstimateUsage obj) {
        return false;
    }
    
    public void EstimateUsageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EstimateUsage.findEstimateUsageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EstimateUsage' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EstimateUsage>();
        for (int i = 0; i < 10; i++) {
            EstimateUsage obj = getNewTransientEstimateUsage(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
