// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.InterfaceImportStock;
import com.vmi.domain.InterfaceImportStockDataOnDemand;
import com.vmi.domain.InterfaceImportStockIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InterfaceImportStockIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InterfaceImportStockIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InterfaceImportStockIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InterfaceImportStockIntegrationTest: @Transactional;
    
    @Autowired
    InterfaceImportStockDataOnDemand InterfaceImportStockIntegrationTest.dod;
    
    @Test
    public void InterfaceImportStockIntegrationTest.testCountInterfaceImportStocks() {
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", dod.getRandomInterfaceImportStock());
        long count = InterfaceImportStock.countInterfaceImportStocks();
        Assert.assertTrue("Counter for 'InterfaceImportStock' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testFindInterfaceImportStock() {
        InterfaceImportStock obj = dod.getRandomInterfaceImportStock();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to provide an identifier", id);
        obj = InterfaceImportStock.findInterfaceImportStock(id);
        Assert.assertNotNull("Find method for 'InterfaceImportStock' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'InterfaceImportStock' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testFindAllInterfaceImportStocks() {
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", dod.getRandomInterfaceImportStock());
        long count = InterfaceImportStock.countInterfaceImportStocks();
        Assert.assertTrue("Too expensive to perform a find all test for 'InterfaceImportStock', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<InterfaceImportStock> result = InterfaceImportStock.findAllInterfaceImportStocks();
        Assert.assertNotNull("Find all method for 'InterfaceImportStock' illegally returned null", result);
        Assert.assertTrue("Find all method for 'InterfaceImportStock' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testFindInterfaceImportStockEntries() {
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", dod.getRandomInterfaceImportStock());
        long count = InterfaceImportStock.countInterfaceImportStocks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<InterfaceImportStock> result = InterfaceImportStock.findInterfaceImportStockEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'InterfaceImportStock' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'InterfaceImportStock' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testFlush() {
        InterfaceImportStock obj = dod.getRandomInterfaceImportStock();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to provide an identifier", id);
        obj = InterfaceImportStock.findInterfaceImportStock(id);
        Assert.assertNotNull("Find method for 'InterfaceImportStock' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInterfaceImportStock(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'InterfaceImportStock' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testMergeUpdate() {
        InterfaceImportStock obj = dod.getRandomInterfaceImportStock();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to provide an identifier", id);
        obj = InterfaceImportStock.findInterfaceImportStock(id);
        boolean modified =  dod.modifyInterfaceImportStock(obj);
        Integer currentVersion = obj.getVersion();
        InterfaceImportStock merged = (InterfaceImportStock)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'InterfaceImportStock' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", dod.getRandomInterfaceImportStock());
        InterfaceImportStock obj = dod.getNewTransientInterfaceImportStock(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'InterfaceImportStock' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'InterfaceImportStock' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InterfaceImportStockIntegrationTest.testRemove() {
        InterfaceImportStock obj = dod.getRandomInterfaceImportStock();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterfaceImportStock' failed to provide an identifier", id);
        obj = InterfaceImportStock.findInterfaceImportStock(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'InterfaceImportStock' with identifier '" + id + "'", InterfaceImportStock.findInterfaceImportStock(id));
    }
    
}
