// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.InterfaceImportStock;
import com.vmi.domain.InterfaceImportStockDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InterfaceImportStockDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InterfaceImportStockDataOnDemand: @Component;
    
    private Random InterfaceImportStockDataOnDemand.rnd = new SecureRandom();
    
    private List<InterfaceImportStock> InterfaceImportStockDataOnDemand.data;
    
    public InterfaceImportStock InterfaceImportStockDataOnDemand.getNewTransientInterfaceImportStock(int index) {
        InterfaceImportStock obj = new InterfaceImportStock();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setInfDate(obj, index);
        setInfLocationCode(obj, index);
        setInfMovementType(obj, index);
        setInfQuantity(obj, index);
        setInfRefPO(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void InterfaceImportStockDataOnDemand.setCreatedBy(InterfaceImportStock obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void InterfaceImportStockDataOnDemand.setCreatedDate(InterfaceImportStock obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void InterfaceImportStockDataOnDemand.setInfDate(InterfaceImportStock obj, int index) {
        Date InfDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setInfDate(InfDate);
    }
    
    public void InterfaceImportStockDataOnDemand.setInfLocationCode(InterfaceImportStock obj, int index) {
        String InfLocationCode = "InfLocationCode_" + index;
        obj.setInfLocationCode(InfLocationCode);
    }
    
    public void InterfaceImportStockDataOnDemand.setInfMovementType(InterfaceImportStock obj, int index) {
        String InfMovementType = "InfMovementType_" + index;
        obj.setInfMovementType(InfMovementType);
    }
    
    public void InterfaceImportStockDataOnDemand.setInfQuantity(InterfaceImportStock obj, int index) {
        Double InfQuantity = new Integer(index).doubleValue();
        obj.setInfQuantity(InfQuantity);
    }
    
    public void InterfaceImportStockDataOnDemand.setInfRefPO(InterfaceImportStock obj, int index) {
        String InfRefPO = "InfRefPO_" + index;
        obj.setInfRefPO(InfRefPO);
    }
    
    public void InterfaceImportStockDataOnDemand.setUpdatedBy(InterfaceImportStock obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void InterfaceImportStockDataOnDemand.setUpdatedDate(InterfaceImportStock obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public InterfaceImportStock InterfaceImportStockDataOnDemand.getSpecificInterfaceImportStock(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InterfaceImportStock obj = data.get(index);
        Long id = obj.getId();
        return InterfaceImportStock.findInterfaceImportStock(id);
    }
    
    public InterfaceImportStock InterfaceImportStockDataOnDemand.getRandomInterfaceImportStock() {
        init();
        InterfaceImportStock obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return InterfaceImportStock.findInterfaceImportStock(id);
    }
    
    public boolean InterfaceImportStockDataOnDemand.modifyInterfaceImportStock(InterfaceImportStock obj) {
        return false;
    }
    
    public void InterfaceImportStockDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = InterfaceImportStock.findInterfaceImportStockEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InterfaceImportStock' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InterfaceImportStock>();
        for (int i = 0; i < 10; i++) {
            InterfaceImportStock obj = getNewTransientInterfaceImportStock(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
