// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.MovementType;
import com.vmi.domain.MovementTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MovementTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MovementTypeDataOnDemand: @Component;
    
    private Random MovementTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<MovementType> MovementTypeDataOnDemand.data;
    
    public MovementType MovementTypeDataOnDemand.getNewTransientMovementType(int index) {
        MovementType obj = new MovementType();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setMoveCode(obj, index);
        setMoveName(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void MovementTypeDataOnDemand.setCreatedBy(MovementType obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void MovementTypeDataOnDemand.setCreatedDate(MovementType obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void MovementTypeDataOnDemand.setMoveCode(MovementType obj, int index) {
        String MoveCode = "MoveCode_" + index;
        obj.setMoveCode(MoveCode);
    }
    
    public void MovementTypeDataOnDemand.setMoveName(MovementType obj, int index) {
        String MoveName = "MoveName_" + index;
        obj.setMoveName(MoveName);
    }
    
    public void MovementTypeDataOnDemand.setUpdatedBy(MovementType obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void MovementTypeDataOnDemand.setUpdatedDate(MovementType obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public MovementType MovementTypeDataOnDemand.getSpecificMovementType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MovementType obj = data.get(index);
        Long id = obj.getId();
        return MovementType.findMovementType(id);
    }
    
    public MovementType MovementTypeDataOnDemand.getRandomMovementType() {
        init();
        MovementType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MovementType.findMovementType(id);
    }
    
    public boolean MovementTypeDataOnDemand.modifyMovementType(MovementType obj) {
        return false;
    }
    
    public void MovementTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MovementType.findMovementTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MovementType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MovementType>();
        for (int i = 0; i < 10; i++) {
            MovementType obj = getNewTransientMovementType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
