// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.MovementType;
import com.vmi.domain.MovementTypeDataOnDemand;
import com.vmi.domain.MovementTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MovementTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MovementTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MovementTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MovementTypeIntegrationTest: @Transactional;
    
    @Autowired
    MovementTypeDataOnDemand MovementTypeIntegrationTest.dod;
    
    @Test
    public void MovementTypeIntegrationTest.testCountMovementTypes() {
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", dod.getRandomMovementType());
        long count = MovementType.countMovementTypes();
        Assert.assertTrue("Counter for 'MovementType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MovementTypeIntegrationTest.testFindMovementType() {
        MovementType obj = dod.getRandomMovementType();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to provide an identifier", id);
        obj = MovementType.findMovementType(id);
        Assert.assertNotNull("Find method for 'MovementType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MovementType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MovementTypeIntegrationTest.testFindAllMovementTypes() {
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", dod.getRandomMovementType());
        long count = MovementType.countMovementTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'MovementType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MovementType> result = MovementType.findAllMovementTypes();
        Assert.assertNotNull("Find all method for 'MovementType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MovementType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MovementTypeIntegrationTest.testFindMovementTypeEntries() {
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", dod.getRandomMovementType());
        long count = MovementType.countMovementTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MovementType> result = MovementType.findMovementTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MovementType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MovementType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MovementTypeIntegrationTest.testFlush() {
        MovementType obj = dod.getRandomMovementType();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to provide an identifier", id);
        obj = MovementType.findMovementType(id);
        Assert.assertNotNull("Find method for 'MovementType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMovementType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MovementType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovementTypeIntegrationTest.testMergeUpdate() {
        MovementType obj = dod.getRandomMovementType();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to provide an identifier", id);
        obj = MovementType.findMovementType(id);
        boolean modified =  dod.modifyMovementType(obj);
        Integer currentVersion = obj.getVersion();
        MovementType merged = (MovementType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MovementType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovementTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", dod.getRandomMovementType());
        MovementType obj = dod.getNewTransientMovementType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MovementType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MovementType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'MovementType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MovementTypeIntegrationTest.testRemove() {
        MovementType obj = dod.getRandomMovementType();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MovementType' failed to provide an identifier", id);
        obj = MovementType.findMovementType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MovementType' with identifier '" + id + "'", MovementType.findMovementType(id));
    }
    
}
