// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.PurchaseOrderBalanceDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseOrderBalanceDataOnDemand_Roo_Configurable {
    
    declare @type: PurchaseOrderBalanceDataOnDemand: @Configurable;
    
}
