// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.PurchaseOrderBalance;
import com.vmi.domain.PurchaseOrderBalanceDataOnDemand;
import com.vmi.domain.PurchaseOrderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PurchaseOrderBalanceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PurchaseOrderBalanceDataOnDemand: @Component;
    
    private Random PurchaseOrderBalanceDataOnDemand.rnd = new SecureRandom();
    
    private List<PurchaseOrderBalance> PurchaseOrderBalanceDataOnDemand.data;
    
    @Autowired
    PurchaseOrderDataOnDemand PurchaseOrderBalanceDataOnDemand.purchaseOrderDataOnDemand;
    
    public PurchaseOrderBalance PurchaseOrderBalanceDataOnDemand.getNewTransientPurchaseOrderBalance(int index) {
        PurchaseOrderBalance obj = new PurchaseOrderBalance();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setPOBalDate(obj, index);
        setPOBalQuantity(obj, index);
        setPOBalUsageQuantity(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setCreatedBy(PurchaseOrderBalance obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setCreatedDate(PurchaseOrderBalance obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setPOBalDate(PurchaseOrderBalance obj, int index) {
        Date POBalDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPOBalDate(POBalDate);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setPOBalQuantity(PurchaseOrderBalance obj, int index) {
        Double POBalQuantity = new Integer(index).doubleValue();
        obj.setPOBalQuantity(POBalQuantity);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setPOBalUsageQuantity(PurchaseOrderBalance obj, int index) {
        Double POBalUsageQuantity = new Integer(index).doubleValue();
        obj.setPOBalUsageQuantity(POBalUsageQuantity);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setUpdatedBy(PurchaseOrderBalance obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void PurchaseOrderBalanceDataOnDemand.setUpdatedDate(PurchaseOrderBalance obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public PurchaseOrderBalance PurchaseOrderBalanceDataOnDemand.getSpecificPurchaseOrderBalance(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PurchaseOrderBalance obj = data.get(index);
        Long id = obj.getId();
        return PurchaseOrderBalance.findPurchaseOrderBalance(id);
    }
    
    public PurchaseOrderBalance PurchaseOrderBalanceDataOnDemand.getRandomPurchaseOrderBalance() {
        init();
        PurchaseOrderBalance obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PurchaseOrderBalance.findPurchaseOrderBalance(id);
    }
    
    public boolean PurchaseOrderBalanceDataOnDemand.modifyPurchaseOrderBalance(PurchaseOrderBalance obj) {
        return false;
    }
    
    public void PurchaseOrderBalanceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PurchaseOrderBalance.findPurchaseOrderBalanceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PurchaseOrderBalance' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PurchaseOrderBalance>();
        for (int i = 0; i < 10; i++) {
            PurchaseOrderBalance obj = getNewTransientPurchaseOrderBalance(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
