// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.RequestDeliveryPlan;
import com.vmi.domain.RequestDeliveryPlanDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RequestDeliveryPlanDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RequestDeliveryPlanDataOnDemand: @Component;
    
    private Random RequestDeliveryPlanDataOnDemand.rnd = new SecureRandom();
    
    private List<RequestDeliveryPlan> RequestDeliveryPlanDataOnDemand.data;
    
    public RequestDeliveryPlan RequestDeliveryPlanDataOnDemand.getNewTransientRequestDeliveryPlan(int index) {
        RequestDeliveryPlan obj = new RequestDeliveryPlan();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setReqDeliDate(obj, index);
        setReqDeliQuantity(obj, index);
        setReqDeliRequestDate(obj, index);
        setReqDeliStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void RequestDeliveryPlanDataOnDemand.setCreatedBy(RequestDeliveryPlan obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setCreatedDate(RequestDeliveryPlan obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setReqDeliDate(RequestDeliveryPlan obj, int index) {
        Date ReqDeliDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReqDeliDate(ReqDeliDate);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setReqDeliQuantity(RequestDeliveryPlan obj, int index) {
        Double ReqDeliQuantity = new Integer(index).doubleValue();
        obj.setReqDeliQuantity(ReqDeliQuantity);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setReqDeliRequestDate(RequestDeliveryPlan obj, int index) {
        Date ReqDeliRequestDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReqDeliRequestDate(ReqDeliRequestDate);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setReqDeliStatus(RequestDeliveryPlan obj, int index) {
        String ReqDeliStatus = "ReqDeliStatus_" + index;
        obj.setReqDeliStatus(ReqDeliStatus);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setUpdatedBy(RequestDeliveryPlan obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void RequestDeliveryPlanDataOnDemand.setUpdatedDate(RequestDeliveryPlan obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public RequestDeliveryPlan RequestDeliveryPlanDataOnDemand.getSpecificRequestDeliveryPlan(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RequestDeliveryPlan obj = data.get(index);
        Long id = obj.getId();
        return RequestDeliveryPlan.findRequestDeliveryPlan(id);
    }
    
    public RequestDeliveryPlan RequestDeliveryPlanDataOnDemand.getRandomRequestDeliveryPlan() {
        init();
        RequestDeliveryPlan obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RequestDeliveryPlan.findRequestDeliveryPlan(id);
    }
    
    public boolean RequestDeliveryPlanDataOnDemand.modifyRequestDeliveryPlan(RequestDeliveryPlan obj) {
        return false;
    }
    
    public void RequestDeliveryPlanDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RequestDeliveryPlan.findRequestDeliveryPlanEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RequestDeliveryPlan' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RequestDeliveryPlan>();
        for (int i = 0; i < 10; i++) {
            RequestDeliveryPlan obj = getNewTransientRequestDeliveryPlan(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
