// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.RequestDeliveryPlan;
import com.vmi.domain.RequestDeliveryPlanDataOnDemand;
import com.vmi.domain.RequestDeliveryPlanIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RequestDeliveryPlanIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RequestDeliveryPlanIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RequestDeliveryPlanIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RequestDeliveryPlanIntegrationTest: @Transactional;
    
    @Autowired
    RequestDeliveryPlanDataOnDemand RequestDeliveryPlanIntegrationTest.dod;
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testCountRequestDeliveryPlans() {
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", dod.getRandomRequestDeliveryPlan());
        long count = RequestDeliveryPlan.countRequestDeliveryPlans();
        Assert.assertTrue("Counter for 'RequestDeliveryPlan' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testFindRequestDeliveryPlan() {
        RequestDeliveryPlan obj = dod.getRandomRequestDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to provide an identifier", id);
        obj = RequestDeliveryPlan.findRequestDeliveryPlan(id);
        Assert.assertNotNull("Find method for 'RequestDeliveryPlan' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RequestDeliveryPlan' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testFindAllRequestDeliveryPlans() {
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", dod.getRandomRequestDeliveryPlan());
        long count = RequestDeliveryPlan.countRequestDeliveryPlans();
        Assert.assertTrue("Too expensive to perform a find all test for 'RequestDeliveryPlan', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RequestDeliveryPlan> result = RequestDeliveryPlan.findAllRequestDeliveryPlans();
        Assert.assertNotNull("Find all method for 'RequestDeliveryPlan' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RequestDeliveryPlan' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testFindRequestDeliveryPlanEntries() {
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", dod.getRandomRequestDeliveryPlan());
        long count = RequestDeliveryPlan.countRequestDeliveryPlans();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RequestDeliveryPlan> result = RequestDeliveryPlan.findRequestDeliveryPlanEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RequestDeliveryPlan' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RequestDeliveryPlan' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testFlush() {
        RequestDeliveryPlan obj = dod.getRandomRequestDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to provide an identifier", id);
        obj = RequestDeliveryPlan.findRequestDeliveryPlan(id);
        Assert.assertNotNull("Find method for 'RequestDeliveryPlan' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRequestDeliveryPlan(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RequestDeliveryPlan' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testMergeUpdate() {
        RequestDeliveryPlan obj = dod.getRandomRequestDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to provide an identifier", id);
        obj = RequestDeliveryPlan.findRequestDeliveryPlan(id);
        boolean modified =  dod.modifyRequestDeliveryPlan(obj);
        Integer currentVersion = obj.getVersion();
        RequestDeliveryPlan merged = (RequestDeliveryPlan)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RequestDeliveryPlan' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", dod.getRandomRequestDeliveryPlan());
        RequestDeliveryPlan obj = dod.getNewTransientRequestDeliveryPlan(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RequestDeliveryPlan' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'RequestDeliveryPlan' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RequestDeliveryPlanIntegrationTest.testRemove() {
        RequestDeliveryPlan obj = dod.getRandomRequestDeliveryPlan();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestDeliveryPlan' failed to provide an identifier", id);
        obj = RequestDeliveryPlan.findRequestDeliveryPlan(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RequestDeliveryPlan' with identifier '" + id + "'", RequestDeliveryPlan.findRequestDeliveryPlan(id));
    }
    
}
