// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.StockLocation;
import com.vmi.domain.StockLocationDataOnDemand;
import com.vmi.domain.StockLocationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockLocationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockLocationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockLocationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StockLocationIntegrationTest: @Transactional;
    
    @Autowired
    StockLocationDataOnDemand StockLocationIntegrationTest.dod;
    
    @Test
    public void StockLocationIntegrationTest.testCountStockLocations() {
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", dod.getRandomStockLocation());
        long count = StockLocation.countStockLocations();
        Assert.assertTrue("Counter for 'StockLocation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockLocationIntegrationTest.testFindStockLocation() {
        StockLocation obj = dod.getRandomStockLocation();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to provide an identifier", id);
        obj = StockLocation.findStockLocation(id);
        Assert.assertNotNull("Find method for 'StockLocation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StockLocation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockLocationIntegrationTest.testFindAllStockLocations() {
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", dod.getRandomStockLocation());
        long count = StockLocation.countStockLocations();
        Assert.assertTrue("Too expensive to perform a find all test for 'StockLocation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StockLocation> result = StockLocation.findAllStockLocations();
        Assert.assertNotNull("Find all method for 'StockLocation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StockLocation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockLocationIntegrationTest.testFindStockLocationEntries() {
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", dod.getRandomStockLocation());
        long count = StockLocation.countStockLocations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StockLocation> result = StockLocation.findStockLocationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StockLocation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StockLocation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockLocationIntegrationTest.testFlush() {
        StockLocation obj = dod.getRandomStockLocation();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to provide an identifier", id);
        obj = StockLocation.findStockLocation(id);
        Assert.assertNotNull("Find method for 'StockLocation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockLocation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StockLocation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockLocationIntegrationTest.testMergeUpdate() {
        StockLocation obj = dod.getRandomStockLocation();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to provide an identifier", id);
        obj = StockLocation.findStockLocation(id);
        boolean modified =  dod.modifyStockLocation(obj);
        Integer currentVersion = obj.getVersion();
        StockLocation merged = (StockLocation)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StockLocation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockLocationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", dod.getRandomStockLocation());
        StockLocation obj = dod.getNewTransientStockLocation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StockLocation' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StockLocation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockLocationIntegrationTest.testRemove() {
        StockLocation obj = dod.getRandomStockLocation();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockLocation' failed to provide an identifier", id);
        obj = StockLocation.findStockLocation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StockLocation' with identifier '" + id + "'", StockLocation.findStockLocation(id));
    }
    
}
