// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.PurchaseOrderDataOnDemand;
import com.vmi.domain.StockLocationDataOnDemand;
import com.vmi.domain.StockMovement;
import com.vmi.domain.StockMovementDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StockMovementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StockMovementDataOnDemand: @Component;
    
    private Random StockMovementDataOnDemand.rnd = new SecureRandom();
    
    private List<StockMovement> StockMovementDataOnDemand.data;
    
    @Autowired
    PurchaseOrderDataOnDemand StockMovementDataOnDemand.purchaseOrderDataOnDemand;
    
    @Autowired
    StockLocationDataOnDemand StockMovementDataOnDemand.stockLocationDataOnDemand;
    
    public StockMovement StockMovementDataOnDemand.getNewTransientStockMovement(int index) {
        StockMovement obj = new StockMovement();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setSMovBalance(obj, index);
        setSMovDate(obj, index);
        setSMovQuantity(obj, index);
        setSMovStatusCode(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void StockMovementDataOnDemand.setCreatedBy(StockMovement obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void StockMovementDataOnDemand.setCreatedDate(StockMovement obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void StockMovementDataOnDemand.setSMovBalance(StockMovement obj, int index) {
        Double SMovBalance = new Integer(index).doubleValue();
        obj.setSMovBalance(SMovBalance);
    }
    
    public void StockMovementDataOnDemand.setSMovDate(StockMovement obj, int index) {
        Date SMovDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setSMovDate(SMovDate);
    }
    
    public void StockMovementDataOnDemand.setSMovQuantity(StockMovement obj, int index) {
        Double SMovQuantity = new Integer(index).doubleValue();
        obj.setSMovQuantity(SMovQuantity);
    }
    
    public void StockMovementDataOnDemand.setSMovStatusCode(StockMovement obj, int index) {
        String SMovStatusCode = "SMovStatusCode_" + index;
        obj.setSMovStatusCode(SMovStatusCode);
    }
    
    public void StockMovementDataOnDemand.setUpdatedBy(StockMovement obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void StockMovementDataOnDemand.setUpdatedDate(StockMovement obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public StockMovement StockMovementDataOnDemand.getSpecificStockMovement(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StockMovement obj = data.get(index);
        Long id = obj.getId();
        return StockMovement.findStockMovement(id);
    }
    
    public StockMovement StockMovementDataOnDemand.getRandomStockMovement() {
        init();
        StockMovement obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StockMovement.findStockMovement(id);
    }
    
    public boolean StockMovementDataOnDemand.modifyStockMovement(StockMovement obj) {
        return false;
    }
    
    public void StockMovementDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StockMovement.findStockMovementEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StockMovement' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StockMovement>();
        for (int i = 0; i < 10; i++) {
            StockMovement obj = getNewTransientStockMovement(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
