// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.StockBalance;
import com.vmi.domain.StockBalanceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect StockBalanceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StockBalanceDataOnDemand: @Component;
    
    private Random StockBalanceDataOnDemand.rnd = new SecureRandom();
    
    private List<StockBalance> StockBalanceDataOnDemand.data;
    
    public StockBalance StockBalanceDataOnDemand.getNewTransientStockBalance(int index) {
        StockBalance obj = new StockBalance();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setSBalDate(obj, index);
        setSBalLocationCode(obj, index);
        setSBalQuantity(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void StockBalanceDataOnDemand.setCreatedBy(StockBalance obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void StockBalanceDataOnDemand.setCreatedDate(StockBalance obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void StockBalanceDataOnDemand.setSBalDate(StockBalance obj, int index) {
        Date SBalDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setSBalDate(SBalDate);
    }
    
    public void StockBalanceDataOnDemand.setSBalLocationCode(StockBalance obj, int index) {
        String SBalLocationCode = "SBalLocationCode_" + index;
        obj.setSBalLocationCode(SBalLocationCode);
    }
    
    public void StockBalanceDataOnDemand.setSBalQuantity(StockBalance obj, int index) {
        Double SBalQuantity = new Integer(index).doubleValue();
        obj.setSBalQuantity(SBalQuantity);
    }
    
    public void StockBalanceDataOnDemand.setUpdatedBy(StockBalance obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void StockBalanceDataOnDemand.setUpdatedDate(StockBalance obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public StockBalance StockBalanceDataOnDemand.getSpecificStockBalance(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StockBalance obj = data.get(index);
        Long id = obj.getId();
        return StockBalance.findStockBalance(id);
    }
    
    public StockBalance StockBalanceDataOnDemand.getRandomStockBalance() {
        init();
        StockBalance obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StockBalance.findStockBalance(id);
    }
    
    public boolean StockBalanceDataOnDemand.modifyStockBalance(StockBalance obj) {
        return false;
    }
    
    public void StockBalanceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StockBalance.findStockBalanceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StockBalance' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StockBalance>();
        for (int i = 0; i < 10; i++) {
            StockBalance obj = getNewTransientStockBalance(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
