// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.StockMovement;
import com.vmi.domain.StockMovementDataOnDemand;
import com.vmi.domain.StockMovementIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockMovementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockMovementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockMovementIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StockMovementIntegrationTest: @Transactional;
    
    @Autowired
    StockMovementDataOnDemand StockMovementIntegrationTest.dod;
    
    @Test
    public void StockMovementIntegrationTest.testCountStockMovements() {
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", dod.getRandomStockMovement());
        long count = StockMovement.countStockMovements();
        Assert.assertTrue("Counter for 'StockMovement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockMovementIntegrationTest.testFindStockMovement() {
        StockMovement obj = dod.getRandomStockMovement();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to provide an identifier", id);
        obj = StockMovement.findStockMovement(id);
        Assert.assertNotNull("Find method for 'StockMovement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StockMovement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockMovementIntegrationTest.testFindAllStockMovements() {
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", dod.getRandomStockMovement());
        long count = StockMovement.countStockMovements();
        Assert.assertTrue("Too expensive to perform a find all test for 'StockMovement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StockMovement> result = StockMovement.findAllStockMovements();
        Assert.assertNotNull("Find all method for 'StockMovement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StockMovement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockMovementIntegrationTest.testFindStockMovementEntries() {
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", dod.getRandomStockMovement());
        long count = StockMovement.countStockMovements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StockMovement> result = StockMovement.findStockMovementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StockMovement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StockMovement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockMovementIntegrationTest.testFlush() {
        StockMovement obj = dod.getRandomStockMovement();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to provide an identifier", id);
        obj = StockMovement.findStockMovement(id);
        Assert.assertNotNull("Find method for 'StockMovement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockMovement(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StockMovement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockMovementIntegrationTest.testMergeUpdate() {
        StockMovement obj = dod.getRandomStockMovement();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to provide an identifier", id);
        obj = StockMovement.findStockMovement(id);
        boolean modified =  dod.modifyStockMovement(obj);
        Integer currentVersion = obj.getVersion();
        StockMovement merged = (StockMovement)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StockMovement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockMovementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", dod.getRandomStockMovement());
        StockMovement obj = dod.getNewTransientStockMovement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StockMovement' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StockMovement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockMovementIntegrationTest.testRemove() {
        StockMovement obj = dod.getRandomStockMovement();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockMovement' failed to provide an identifier", id);
        obj = StockMovement.findStockMovement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StockMovement' with identifier '" + id + "'", StockMovement.findStockMovement(id));
    }
    
}
