// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.StockBalance;
import com.vmi.domain.StockBalanceDataOnDemand;
import com.vmi.domain.StockBalanceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockBalanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockBalanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockBalanceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StockBalanceIntegrationTest: @Transactional;
    
    @Autowired
    StockBalanceDataOnDemand StockBalanceIntegrationTest.dod;
    
    @Test
    public void StockBalanceIntegrationTest.testCountStockBalances() {
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", dod.getRandomStockBalance());
        long count = StockBalance.countStockBalances();
        Assert.assertTrue("Counter for 'StockBalance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockBalanceIntegrationTest.testFindStockBalance() {
        StockBalance obj = dod.getRandomStockBalance();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to provide an identifier", id);
        obj = StockBalance.findStockBalance(id);
        Assert.assertNotNull("Find method for 'StockBalance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StockBalance' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockBalanceIntegrationTest.testFindAllStockBalances() {
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", dod.getRandomStockBalance());
        long count = StockBalance.countStockBalances();
        Assert.assertTrue("Too expensive to perform a find all test for 'StockBalance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StockBalance> result = StockBalance.findAllStockBalances();
        Assert.assertNotNull("Find all method for 'StockBalance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StockBalance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockBalanceIntegrationTest.testFindStockBalanceEntries() {
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", dod.getRandomStockBalance());
        long count = StockBalance.countStockBalances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StockBalance> result = StockBalance.findStockBalanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StockBalance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StockBalance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockBalanceIntegrationTest.testFlush() {
        StockBalance obj = dod.getRandomStockBalance();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to provide an identifier", id);
        obj = StockBalance.findStockBalance(id);
        Assert.assertNotNull("Find method for 'StockBalance' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockBalance(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StockBalance' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockBalanceIntegrationTest.testMergeUpdate() {
        StockBalance obj = dod.getRandomStockBalance();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to provide an identifier", id);
        obj = StockBalance.findStockBalance(id);
        boolean modified =  dod.modifyStockBalance(obj);
        Integer currentVersion = obj.getVersion();
        StockBalance merged = (StockBalance)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StockBalance' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockBalanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", dod.getRandomStockBalance());
        StockBalance obj = dod.getNewTransientStockBalance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StockBalance' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StockBalance' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockBalanceIntegrationTest.testRemove() {
        StockBalance obj = dod.getRandomStockBalance();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StockBalance' failed to provide an identifier", id);
        obj = StockBalance.findStockBalance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StockBalance' with identifier '" + id + "'", StockBalance.findStockBalance(id));
    }
    
}
