// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.vmi.domain;

import com.vmi.domain.ItemDataOnDemand;
import com.vmi.domain.StockLocation;
import com.vmi.domain.StockLocationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StockLocationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StockLocationDataOnDemand: @Component;
    
    private Random StockLocationDataOnDemand.rnd = new SecureRandom();
    
    private List<StockLocation> StockLocationDataOnDemand.data;
    
    @Autowired
    ItemDataOnDemand StockLocationDataOnDemand.itemDataOnDemand;
    
    public StockLocation StockLocationDataOnDemand.getNewTransientStockLocation(int index) {
        StockLocation obj = new StockLocation();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setSLocCode(obj, index);
        setSLocCurrentQuantity(obj, index);
        setSLocMax(obj, index);
        setSLocMin(obj, index);
        setSLocName(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void StockLocationDataOnDemand.setCreatedBy(StockLocation obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void StockLocationDataOnDemand.setCreatedDate(StockLocation obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void StockLocationDataOnDemand.setSLocCode(StockLocation obj, int index) {
        String SLocCode = "SLocCode_" + index;
        obj.setSLocCode(SLocCode);
    }
    
    public void StockLocationDataOnDemand.setSLocCurrentQuantity(StockLocation obj, int index) {
        Double SLocCurrentQuantity = new Integer(index).doubleValue();
        obj.setSLocCurrentQuantity(SLocCurrentQuantity);
    }
    
    public void StockLocationDataOnDemand.setSLocMax(StockLocation obj, int index) {
        Integer SLocMax = new Integer(index);
        obj.setSLocMax(SLocMax);
    }
    
    public void StockLocationDataOnDemand.setSLocMin(StockLocation obj, int index) {
        Integer SLocMin = new Integer(index);
        obj.setSLocMin(SLocMin);
    }
    
    public void StockLocationDataOnDemand.setSLocName(StockLocation obj, int index) {
        String SLocName = "SLocName_" + index;
        obj.setSLocName(SLocName);
    }
    
    public void StockLocationDataOnDemand.setUpdatedBy(StockLocation obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void StockLocationDataOnDemand.setUpdatedDate(StockLocation obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public StockLocation StockLocationDataOnDemand.getSpecificStockLocation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StockLocation obj = data.get(index);
        Long id = obj.getId();
        return StockLocation.findStockLocation(id);
    }
    
    public StockLocation StockLocationDataOnDemand.getRandomStockLocation() {
        init();
        StockLocation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StockLocation.findStockLocation(id);
    }
    
    public boolean StockLocationDataOnDemand.modifyStockLocation(StockLocation obj) {
        return false;
    }
    
    public void StockLocationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StockLocation.findStockLocationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StockLocation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StockLocation>();
        for (int i = 0; i < 10; i++) {
            StockLocation obj = getNewTransientStockLocation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
